Pr 178/mobile navbar
smartcontractkit/blockchain-developer-hub pull request #185
Opened 2022-04-22 13:43 UTC by hdJerry

![Screenshot from 2022-04-22 14-38-11](https://user-images.githubusercontent.com/28502531/164725590-a790bc6a-e016-4b15-bdcc-4368cef25d01.png)

![Screenshot from 2022-04-22 14-37-26](https://user-images.githubusercontent.com/28502531/164725538-301ed6db-06a1-4895-9530-ab02d6e92c1b.png)

2022-04-25 08:07 UTC, Zelig880 requested changes
The storybook story has not been updated as requested by the Story. Please update

2022-04-25 09:28 UTC, hdJerry commented
> The storybook story has not been updated as requested by the Story. Please update

The Story book for the navbar itself will be for this and this is the responsive of the navbar except we are to create its as a component of its own.

2022-04-28 13:41 UTC, markshenouda requested changes

2022-04-28 13:41 UTC, markshenouda commented on src/components/NavBar/NavBar.jsx
> +    document.body.style.overflow = value ? 'hidden' : 'auto';
As Dustin said before accessing dom is expensive in React! We should find another way to do it

2022-04-28 13:41 UTC, markshenouda commented on src/components/NavBar/NavBar.module.css
>  }
I'd recommend adding a z-index here so you can avoid this small bug


https://user-images.githubusercontent.com/49324987/165765309-40bc70a7-99f0-4741-861b-ac7479388bc2.mov


https://user-images.githubusercontent.com/49324987/165765309-40bc70a7-99f0-4741-861b-ac7479388bc2.mov



https://user-images.githubusercontent.com/49324987/165765149-c0ae574f-d54c-4acc-8ced-8b8e2e0c4f54.mov

2022-04-28 13:41 UTC, markshenouda commented on src/components/NavBar/NavBar.module.css
>  }
I'd recommend adding a z-index here so you can avoid this small bug


https://user-images.githubusercontent.com/49324987/165765309-40bc70a7-99f0-4741-861b-ac7479388bc2.mov


https://user-images.githubusercontent.com/49324987/165765309-40bc70a7-99f0-4741-861b-ac7479388bc2.mov



https://user-images.githubusercontent.com/49324987/165765149-c0ae574f-d54c-4acc-8ced-8b8e2e0c4f54.mov

2022-04-28 15:19 UTC, markshenouda approved these changes

2022-04-28 15:26 UTC, merged